import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, symlinkSync, lstatSync } from 'node:fs'
import { dirname, join } from 'node:path'

interface JcodeWiringOptions {
  targetRoot: string
  dryRun?: boolean
  quiet?: boolean
}

const SKILLS = [
  {
    name: 'lazy-init',
    description: 'Bootstrap lazy-harness on a host project.',
    usage: '.lazy-harness/bin/lazy init --target <dir> [--dry-run|--force]'
  },
  {
    name: 'lazy-sync',
    description: 'Sync framework Category A from the recorded source checkout while preserving host memory.',
    usage: '.lazy-harness/bin/lazy sync [--dry-run|--force]'
  },
  {
    name: 'lazy-update',
    description: 'Fetch the latest lazy-harness source and sync this host.',
    usage: '.lazy-harness/bin/lazy update [--dry-run|--force|--ref <ref>]'
  },
  {
    name: 'lazy-doctor',
    description: 'Run lazy-harness health/audit checks.',
    usage: '.lazy-harness/bin/lazy doctor --profile=smoke'
  },
  {
    name: 'lazy-test',
    description: 'Run lazy-harness reproducible self-test for the host.',
    usage: '.lazy-harness/bin/lazy test'
  }
]

const GENERATED_MARKER = 'Generated by lazy-harness. Local edits below this line make the file user-owned.'

function log(options: JcodeWiringOptions, message: string): void {
  if (!options.quiet) console.log(message)
}

function ensureDir(options: JcodeWiringOptions, dir: string): void {
  if (options.dryRun) {
    log(options, `  [dry] mkdir ${dir}`)
    return
  }
  mkdirSync(dir, { recursive: true })
}

function managedContent(content: string): string {
  const marker = `# ${GENERATED_MARKER}\n`
  if (content.startsWith('#!')) {
    const firstNewline = content.indexOf('\n')
    if (firstNewline >= 0) return `${content.slice(0, firstNewline + 1)}${marker}${content.slice(firstNewline + 1)}`
  }
  if (content.startsWith('---\n')) {
    const frontmatterEnd = content.indexOf('\n---\n', 4)
    if (frontmatterEnd >= 0) {
      const insertAt = frontmatterEnd + '\n---\n'.length
      return `${content.slice(0, insertAt)}${marker}${content.slice(insertAt)}`
    }
  }
  return `${marker}${content}`
}

function writeManaged(options: JcodeWiringOptions, path: string, content: string, mode = 0o644): void {
  const nextContent = managedContent(content)
  if (existsSync(path)) {
    const existing = readFileSync(path, 'utf8')
    if (!existing.includes(GENERATED_MARKER)) {
      log(options, `  ✓ keep user-owned ${path}`)
      return
    }
    if (existing === nextContent) {
      log(options, `  ✓ unchanged ${path}`)
      return
    }
    if (options.dryRun) {
      log(options, `  [dry] update generated ${path}`)
      return
    }
    writeFileSync(path, nextContent, { mode })
    if (mode & 0o111) chmodSync(path, mode)
    log(options, `  ✓ updated generated ${path}`)
    return
  }
  if (options.dryRun) {
    log(options, `  [dry] write ${path}`)
    return
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, nextContent, { mode })
  if (mode & 0o111) chmodSync(path, mode)
  log(options, `  ✓ wrote ${path}`)
}

function ensureLazyHarnessInstruction(options: JcodeWiringOptions): void {
  const path = join(options.targetRoot, '.jcode', 'harness', '05-lazy-harness.md')
  if (existsSync(path)) {
    log(options, `  ✓ keep existing ${path}`)
    return
  }
  if (options.dryRun) {
    log(options, `  [dry] symlink ${path} -> ../../.lazy-harness/AGENTS.md`)
    return
  }
  mkdirSync(dirname(path), { recursive: true })
  try {
    symlinkSync('../../.lazy-harness/AGENTS.md', path)
    log(options, `  ✓ symlinked ${path}`)
  } catch {
    const source = join(options.targetRoot, '.lazy-harness', 'AGENTS.md')
    const content = existsSync(source)
      ? readFileSync(source, 'utf8')
      : '# Lazy-Harness instructions\n\nMissing .lazy-harness/AGENTS.md. Re-run lazy update.\n'
    writeFileSync(path, content)
    log(options, `  ✓ copied lazy-harness instructions to ${path}`)
  }
}

function projectAgents(): string {
  return `# Private Jcode Harness\n\nThis directory is project-local/private Jcode wiring generated by lazy-harness.\n\n## Intent\n\n- Load .lazy-harness/AGENTS.md every session through .jcode/harness/05-lazy-harness.md.\n- Keep .jcode/ local/private by default. It is added to .git/info/exclude by lazy-init.\n- Preserve team/project AGENTS.md unless .jcode/config.toml explicitly changes ignore_project_agents.\n\n## Working style\n\n- Read lazy-harness records before host-specific implementation.\n- Run focused validation after code changes.\n- Avoid destructive actions unless explicitly requested.\n`
}

function routingPolicy(): string {
  return `# Jcode Agent Routing Policy\n\nUse subagents only when they reduce risk or speed up real progress.\n\n- Planning/architecture: planner, metis, reviewer.\n- Concrete implementation: coder, hephaestus, executor.\n- Unknown codebase area: searcher, librarian, atlas, explore.\n- Difficult debugging: sisyphus, oracle.\n- Visual/UI inspection: visual, multimodal-looker.\n`
}

function projectRules(): string {
  return `# Project-specific Jcode Notes\n\nThis file is intentionally local to the host project. Add project-specific workflow notes here.\n\n## Lazy-harness wiring\n\n- .jcode/harness/05-lazy-harness.md points at .lazy-harness/AGENTS.md.\n- .jcode/config.toml enables Jcode private hooks and lazy-harness lifecycle hooks.\n- .jcode/ is local/private and should stay untracked.\n`
}

function configToml(): string {
  return `# Project-local Jcode harness config generated by lazy-harness.\n# Local-only: .jcode/ is excluded via .git/info/exclude.\n\n[prompt]\nignore_project_agents = false\nignore_global_agents = false\nload_jcode_agents = true\nload_harness_dir = true\n# Optional M45+ private instruction globs, relative to .jcode/.\nprivate_instructions = [\"rules/*.md\", \"monorepo/*/AGENTS.md\"]\n\n[hooks]\nenabled = true\n\n[[hooks.commands]]\nevent = \"tool.execute.before\"\ntool = \"bash\"\ncommand = \".jcode/hooks/check-bash.sh\"\nblocking = true\ntimeout_ms = 3000\n\n[[hooks.commands]]\nevent = \"tool.execute.before\"\ntool = \"edit\"\ncommand = \".lazy-harness/hooks/lifecycle/on-tool-execute-before.sh\"\nblocking = true\ntimeout_ms = 3000\n\n[[hooks.commands]]\nevent = \"tool.execute.before\"\ntool = \"write\"\ncommand = \".lazy-harness/hooks/lifecycle/on-tool-execute-before.sh\"\nblocking = true\ntimeout_ms = 3000\n\n[[hooks.commands]]\nevent = \"tool.execute.before\"\ntool = \"multiedit\"\ncommand = \".lazy-harness/hooks/lifecycle/on-tool-execute-before.sh\"\nblocking = true\ntimeout_ms = 3000\n\n[[hooks.commands]]\nevent = \"response.completed\"\ntool = \"*\"\ncommand = \".lazy-harness/hooks/lifecycle/on-response-completed.sh\"\nblocking = false\ntimeout_ms = 5000\n\n[[hooks.commands]]\nevent = \"tool.execute.after\"\ntool = \"*\"\ncommand = \".jcode/hooks/log-tool.sh\"\nblocking = false\ntimeout_ms = 3000\n`
}

function checkBashHook(): string {
  return `#!/usr/bin/env bash\nset -euo pipefail\n\npayload=$(cat || true)\n\npython3 - \"$payload\" <<'PY'\nimport json\nimport re\nimport sys\n\npayload = sys.argv[1] if len(sys.argv) > 1 else \"\"\ntry:\n    data = json.loads(payload) if payload.strip() else {}\nexcept Exception:\n    data = {\"raw\": payload}\n\nblob = json.dumps(data, ensure_ascii=False)\nblocked = [\n    (r\"\\brm\\s+-rf\\s+/(?:[\\s\\\\\\\"\\x27}\\]]|$)\", \"Refusing rm -rf /\"),\n    (r\"\\bsudo\\s+rm\\s+-rf\\s+/(?:[\\s\\\\\\\"\\x27}\\]]|$)\", \"Refusing sudo rm -rf /\"),\n    (r\"\\bdd\\s+.*\\bof=/dev/(sd|nvme|vd)\", \"Refusing raw disk overwrite\"),\n    (r\"\\bmkfs(?:\\.[a-z0-9]+)?\\s+/dev/\", \"Refusing filesystem creation on block device\"),\n]\n\nfor pattern, reason in blocked:\n    if re.search(pattern, blob, re.IGNORECASE | re.DOTALL):\n        print(json.dumps({\"action\": \"deny\", \"reason\": reason}))\n        sys.exit(0)\n\nprint(json.dumps({\"action\": \"allow\"}))\nPY\n`
}

function logToolHook(): string {
  return `#!/usr/bin/env bash\nset -euo pipefail\n\nmkdir -p .jcode/hooks\npayload=$(cat || true)\nprintf '%s %s\\n' \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \"$payload\" >> .jcode/hooks/tool-events.jsonl\nexit 0\n`
}

function skillMarkdown(name: string, description: string, usage: string): string {
  return `---\nname: ${name}\ndescription: ${description}\nallowed-tools: bash, read, grep\n---\n\n# ${name}\n\n${description}\n\nRun from the host project root:\n\n\`\`\`bash\n${usage}\n\`\`\`\n\nThis skill delegates to the installed .lazy-harness framework. Do not edit generated framework files directly in the host; use lazy update/sync.\n`
}

export function installJcodeWiring(options: JcodeWiringOptions): void {
  log(options, '\n[Jcode] Project-local private wiring')
  const root = options.targetRoot
  ensureDir(options, join(root, '.jcode'))
  ensureDir(options, join(root, '.jcode', 'harness'))
  ensureDir(options, join(root, '.jcode', 'hooks'))
  ensureDir(options, join(root, '.jcode', 'skills'))
  ensureDir(options, join(root, '.jcode', 'rules'))
  ensureDir(options, join(root, '.jcode', 'monorepo'))

  writeManaged(options, join(root, '.jcode', 'AGENTS.md'), projectAgents())
  writeManaged(options, join(root, '.jcode', 'config.toml'), configToml())
  ensureLazyHarnessInstruction(options)
  writeManaged(options, join(root, '.jcode', 'harness', '10-routing-policy.md'), routingPolicy())
  writeManaged(options, join(root, '.jcode', 'harness', '20-project-rules.md'), projectRules())
  writeManaged(options, join(root, '.jcode', 'hooks', 'check-bash.sh'), checkBashHook(), 0o755)
  writeManaged(options, join(root, '.jcode', 'hooks', 'log-tool.sh'), logToolHook(), 0o755)

  for (const skill of SKILLS) {
    writeManaged(
      options,
      join(root, '.jcode', 'skills', skill.name, 'SKILL.md'),
      skillMarkdown(skill.name, skill.description, skill.usage)
    )
  }

  const instructionPath = join(root, '.jcode', 'harness', '05-lazy-harness.md')
  if (!options.dryRun && existsSync(instructionPath)) {
    try {
      const stat = lstatSync(instructionPath)
      if (!stat.isSymbolicLink()) log(options, `  ℹ ${instructionPath} is a regular file fallback`)
    } catch {
      // ignore
    }
  }
}
