#!/usr/bin/env bun
import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { createHash } from 'node:crypto'

const GENERATED_MARKER = 'Generated by lazy-harness. Local edits below this line make the file user-owned.'
const NAME_RE = /^[a-z][a-z0-9-]{1,63}$/
const SCRIPT_RE = /^[a-zA-Z0-9._-]+$/

interface Args {
  command: string
  name: string
  description: string
  usage: string
  script?: string
  allowedTools: string
  force: boolean
  dryRun: boolean
  target: string
}

function usage(exitCode = 0): never {
  const out = exitCode === 0 ? console.log : console.error
  out(`Usage: lazy skill create <name> [options]

Create a project-local custom Jcode skill.

Options:
  --description <text>       Skill description
  --usage <text>             Command/example shown in SKILL.md
  --script <file>            Also create .jcode/skills/<name>/scripts/<file>
  --allowed-tools <list>     Frontmatter allowed-tools (default: bash, read, grep)
  --target <dir>             Host root (default: cwd)
  --force                    Overwrite generated files
  --dry-run                  Print planned writes only
  -h, --help                 Show this help
`)
  process.exit(exitCode)
}

function nextValue(argv: string[], index: number, flag: string): string {
  const value = argv[index + 1]
  if (!value || value.startsWith('--')) {
    console.error(`Missing value for ${flag}`)
    process.exit(2)
  }
  return value
}

function parseArgs(argv: string[]): Args {
  if (argv[0] === '--help' || argv[0] === '-h' || argv.length === 0) usage(argv.length === 0 ? 2 : 0)
  const command = argv[0]
  if (command !== 'create') {
    console.error(`Unknown skill command: ${command}`)
    usage(2)
  }
  const name = argv[1]
  if (!name || name.startsWith('--')) {
    console.error('Missing skill name')
    usage(2)
  }
  const args: Args = {
    command,
    name,
    description: `Project-local Jcode skill: ${name}`,
    usage: `# Add the command or workflow for ${name}`,
    allowedTools: 'bash, read, grep',
    force: false,
    dryRun: false,
    target: process.cwd(),
  }
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--description') args.description = nextValue(argv, i++, a)
    else if (a.startsWith('--description=')) args.description = a.slice('--description='.length)
    else if (a === '--usage') args.usage = nextValue(argv, i++, a)
    else if (a.startsWith('--usage=')) args.usage = a.slice('--usage='.length)
    else if (a === '--script') args.script = nextValue(argv, i++, a)
    else if (a.startsWith('--script=')) args.script = a.slice('--script='.length)
    else if (a === '--allowed-tools') args.allowedTools = nextValue(argv, i++, a)
    else if (a.startsWith('--allowed-tools=')) args.allowedTools = a.slice('--allowed-tools='.length)
    else if (a === '--target') args.target = nextValue(argv, i++, a)
    else if (a.startsWith('--target=')) args.target = a.slice('--target='.length)
    else if (a === '--force') args.force = true
    else if (a === '--dry-run') args.dryRun = true
    else if (a === '--help' || a === '-h') usage(0)
    else {
      console.error(`Unknown option: ${a}`)
      usage(2)
    }
  }
  return args
}

function validate(args: Args): void {
  if (!NAME_RE.test(args.name)) {
    console.error(`Invalid skill name '${args.name}'. Use ${NAME_RE}`)
    process.exit(2)
  }
  if (args.script) {
    if (!SCRIPT_RE.test(args.script) || args.script.includes('/') || args.script.includes('..')) {
      console.error(`Invalid script name '${args.script}'. Use a simple filename without slashes or '..'.`)
      process.exit(2)
    }
  }
}

function managed(content: string): string {
  return `# ${GENERATED_MARKER}\n${content}`
}

function skillMarkdown(args: Args): string {
  return `---
name: ${args.name}
description: ${args.description.replace(/\n/g, ' ')}
allowed-tools: ${args.allowedTools.replace(/\n/g, ' ')}
---
# ${GENERATED_MARKER}

# ${args.name}

${args.description}

## Usage

\`\`\`bash
${args.usage}
\`\`\`

## Source of truth

- Custom skill wrapper: \`.jcode/skills/${args.name}/SKILL.md\`
- Creation log: \`.lazy-harness/knowledge/skills.jsonl\`
- If this skill encodes a project/team policy, record that policy in \`.lazy-harness\` records and link it here.
${args.script ? `- Optional script: \`.jcode/skills/${args.name}/scripts/${args.script}\`\n` : ''}
`
}

function scriptContent(args: Args): string {
  return `#!/usr/bin/env bash
# ${GENERATED_MARKER}
set -euo pipefail

# Project-local helper for .jcode/skills/${args.name}/SKILL.md.
# Fill in the workflow, or delegate to a canonical .lazy-harness script/record.

echo "${args.name}: customize .jcode/skills/${args.name}/scripts/${args.script}"
`
}

function writeManaged(path: string, content: string, args: Args, mode = 0o644): 'created' | 'updated' | 'skipped' {
  if (existsSync(path)) {
    const existing = readFileSync(path, 'utf8')
    if (!existing.includes(GENERATED_MARKER) && !args.force) {
      console.error(`Refusing to overwrite user-owned file: ${path}`)
      console.error('Pass --force only after reviewing the existing file.')
      process.exit(3)
    }
    if (existing === content) {
      console.log(`  ✓ unchanged ${path}`)
      return 'skipped'
    }
    if (args.dryRun) {
      console.log(`  [dry] update ${path}`)
      return 'updated'
    }
    writeFileSync(path, content, { mode })
    if (mode & 0o111) chmodSync(path, mode)
    console.log(`  ✓ updated ${path}`)
    return 'updated'
  }
  if (args.dryRun) {
    console.log(`  [dry] create ${path}`)
    return 'created'
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, { mode })
  if (mode & 0o111) chmodSync(path, mode)
  console.log(`  ✓ created ${path}`)
  return 'created'
}

function appendMetadata(targetRoot: string, args: Args, skillPath: string, scriptPath: string | undefined, status: string): void {
  const relSkill = skillPath.replace(`${targetRoot}/`, '')
  const relScript = scriptPath?.replace(`${targetRoot}/`, '')
  const createdAt = new Date().toISOString()
  const id = 'skill_' + createHash('sha1').update(`${args.name}:${createdAt}`).digest('hex').slice(0, 12)
  const entry: Record<string, unknown> = {
    id,
    createdAt,
    source: 'lazy skill create',
    skillName: args.name,
    skillPath: relSkill,
    description: args.description,
    allowedTools: args.allowedTools,
    usage: args.usage,
    status,
  }
  if (relScript) entry.scriptPath = relScript
  const logPath = join(targetRoot, '.lazy-harness', 'knowledge', 'skills.jsonl')
  if (args.dryRun) {
    console.log(`  [dry] append metadata ${logPath}`)
    return
  }
  mkdirSync(dirname(logPath), { recursive: true })
  appendFileSync(logPath, JSON.stringify(entry, null, 0) + '\n')
  console.log(`  ✓ logged ${logPath}`)
}

function main(): void {
  const args = parseArgs(process.argv.slice(2))
  validate(args)
  const targetRoot = resolve(args.target)
  if (!existsSync(join(targetRoot, '.lazy-harness'))) {
    console.error(`Target does not contain .lazy-harness/: ${targetRoot}`)
    process.exit(2)
  }

  console.log('lazy skill create')
  console.log(`  target: ${targetRoot}`)
  console.log(`  skill:  ${args.name}`)
  if (args.dryRun) console.log('  mode:   DRY-RUN')

  const skillPath = join(targetRoot, '.jcode', 'skills', args.name, 'SKILL.md')
  const skillStatus = writeManaged(skillPath, skillMarkdown(args), args)
  let scriptPath: string | undefined
  let scriptStatus: 'created' | 'updated' | 'skipped' | undefined
  if (args.script) {
    scriptPath = join(targetRoot, '.jcode', 'skills', args.name, 'scripts', args.script)
    scriptStatus = writeManaged(scriptPath, scriptContent(args), args, 0o755)
  }
  const finalStatus = skillStatus === 'created' || scriptStatus === 'created' ? 'created' : 'updated'
  appendMetadata(targetRoot, args, skillPath, scriptPath, finalStatus)
  console.log('✓ custom skill ready')
}

main()
